### ISSUE TITLE
Doesn't work on Android 15

### ISSUE THREAD

**Issue by bottomtextboy** [nongthaihoang/custom_font_installer#11]
Installing it (at least on Pixel) changes the font into Roboto rather than the fonts in the folder

**Comment by Fishawyyy** [comment]
Same as above. Plus, it doesn't really change fonts system-wide (status bar and settings stay stock).

**Comment by Mr-FreeBird** [comment]
Luckily it's very easy to fix this by doing the following:

• Flash GSP, reboot.
• Create a font_fallback.xml in /data/adb/modules/googlesansprime/system/etc with the same content as the font.xml from the same folder but with version="23" removed.
• Reboot and you're done.

I can't credit who come up with this solution because that's unknown to me.

**Comment by RealTimeyt** [comment]
> Luckily it's very easy to fix this by doing the following:
> 
> • Flash GSP, reboot. • Create a font_fallback.xml in /data/adb/modules/googlesansprime/system/etc with the same content as the font.xml from the same folder but with version="23" removed. • Reboot and you're done.
> 
> I can't credit who came up with this solution because that's unknown to me.

I suppose I did something wrong but this just makes my PIxel unable to boot?

**Comment by nongthaihoang** [comment]
Thank you all for reporting. I'll update the module soon.

**Comment by bottomtextboy** [comment]
> Thank you all for reporting. I'll update the module soon.

thank you man, you're goated

**Comment by nongthaihoang** [comment]
Updated
